### ISSUE TITLE
Is deepr runtime ready for production use?

### ISSUE THREAD

**Issue by ansarizafar** [medmain/deepr#8]
I really like deepr and I think its better than graphql. I want to use deepr with [EdgeDb](https://edgedb.com) and [Svelte](https://svelte.dev). Is deepr runtme ready for production use?

**Comment by mvila** [comment]
Thanks, @ansarizafar for your positive feedback. I think the runtime is good enough to be used in production but since the all thing (i.e. Deepr specs) is still a work in progress, I would recommend starting with a small project.
